// <auto-generated />
namespace OnlineMovieRental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class customermodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(customermodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202007181141559_customermodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
